version: '3'
services:

  php-apache:
    container_name: api-cabs
    build:
      context: .
      dockerfile: ./docker/php-apache/Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_VERSION=${POSTGRES_VERSION}
    restart: 'no'
    volumes:
      - ./app:/var/www/html
    ports:
      - ${API_HTTP_PORT}:80

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./docker/database:/var/lib/postgresql/data:rw

volumes:
    mysql:
